spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_data?serverTimezone=UTC
    username: root
    password: 981103
  jpa:
    hibernate:
      #     更新或者创建数据表结构
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #    控制台显示SQL
    show-sql: true